Minor changes, and starting support for gu driver (based on linux framebuffer implementation.

diff --git a/PSP/Plugins/APP_Links2/links-2.1pre22/build-psp/configure-psp b/PSP/Plugins/APP_Links2/links-2.1pre22/build-psp/configure-psp
--- a/PSP/Plugins/APP_Links2/links-2.1pre22/build-psp/configure-psp
+++ b/PSP/Plugins/APP_Links2/links-2.1pre22/build-psp/configure-psp
@@ -17,7 +17,7 @@ echo "Creating dummy dl library so configure can finish..."
 touch $SHAREDLIB_DIR/lib/libdl.a
 
 echo "Calling configure..."
-../configure --prefix=$(psp-config --psp-prefix) --srcdir=../ --target=psp --includedir=$PSPDEV/psp/sdk/include/ --enable-javascript --enable-graphics --without-svgalib --without-x --without-fb --without-directfb --without-pmshell --without-atheos --without-sdl --without-pspgu --with-ssl || (echo "Error configuring links2" ; exit 0);
+../configure --prefix=$(psp-config --psp-prefix) --srcdir=../ --target=psp --includedir=$PSPDEV/psp/sdk/include/ --enable-javascript --enable-graphics --without-svgalib --without-x --without-fb --without-directfb --without-pmshell --without-atheos --without-sdl --with-pspsdl --without-pspgu --with-ssl || (echo "Error configuring links2" ; exit 0);
 
 echo "include Makefile.psp" >> Makefile
 echo "Done."
